package com.pet.yxy.mapper;

import com.pet.yxy.pojo.CustomerMessage;

public interface CustomerMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_message
     *
     * @mbggenerated
     */
    int insert(CustomerMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_message
     *
     * @mbggenerated
     */
    int insertSelective(CustomerMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_message
     *
     * @mbggenerated
     */
    CustomerMessage selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerMessage record);
}