package com.pet.yz.mapper;

import com.pet.yz.pojo.PayInfo;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated
     */
    PayInfo selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayInfo record);

}