package com.pet.yz.mapper;

import com.pet.yz.pojo.PayPlatform;

public interface PayPlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer platformId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform
     *
     * @mbggenerated
     */
    int insert(PayPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform
     *
     * @mbggenerated
     */
    int insertSelective(PayPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform
     *
     * @mbggenerated
     */
    PayPlatform selectByPrimaryKey(Integer platformId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_platform
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayPlatform record);
}