package com.pet.yz.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class PayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.pay_id
     *
     * @mbggenerated
     */
    private Integer payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.platform_id
     *
     * @mbggenerated
     */
    private Integer platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.is_success
     *
     * @mbggenerated
     */
    private Boolean isSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_info.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.pay_id
     *
     * @return the value of pay_info.pay_id
     *
     * @mbggenerated
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.pay_id
     *
     * @param payId the value for pay_info.pay_id
     *
     * @mbggenerated
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.platform_id
     *
     * @return the value of pay_info.platform_id
     *
     * @mbggenerated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.platform_id
     *
     * @param platformId the value for pay_info.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.customer_id
     *
     * @return the value of pay_info.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.customer_id
     *
     * @param customerId the value for pay_info.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.order_id
     *
     * @return the value of pay_info.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.order_id
     *
     * @param orderId the value for pay_info.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.serial_number
     *
     * @return the value of pay_info.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.serial_number
     *
     * @param serialNumber the value for pay_info.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.money
     *
     * @return the value of pay_info.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.money
     *
     * @param money the value for pay_info.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.is_success
     *
     * @return the value of pay_info.is_success
     *
     * @mbggenerated
     */
    public Boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.is_success
     *
     * @param isSuccess the value for pay_info.is_success
     *
     * @mbggenerated
     */
    public void setIsSuccess(Boolean isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.create_time
     *
     * @return the value of pay_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.create_time
     *
     * @param createTime the value for pay_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_info.status
     *
     * @return the value of pay_info.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_info.status
     *
     * @param status the value for pay_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "PayInfo{" +
                "payId=" + payId +
                ", platformId=" + platformId +
                ", customerId=" + customerId +
                ", orderId=" + orderId +
                ", serialNumber='" + serialNumber + '\'' +
                ", money=" + money +
                ", isSuccess=" + isSuccess +
                ", createTime=" + createTime +
                ", status=" + status +
                '}';
    }
}