package com.pet.yz.pojo;

import java.util.Date;

public class PayPlatform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_platform.platform_id
     *
     * @mbggenerated
     */
    private Integer platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_platform.platform_name
     *
     * @mbggenerated
     */
    private String platformName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_platform.platform_icon
     *
     * @mbggenerated
     */
    private String platformIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_platform.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_platform.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_platform.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_platform.platform_id
     *
     * @return the value of pay_platform.platform_id
     *
     * @mbggenerated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_platform.platform_id
     *
     * @param platformId the value for pay_platform.platform_id
     *
     * @mbggenerated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_platform.platform_name
     *
     * @return the value of pay_platform.platform_name
     *
     * @mbggenerated
     */
    public String getPlatformName() {
        return platformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_platform.platform_name
     *
     * @param platformName the value for pay_platform.platform_name
     *
     * @mbggenerated
     */
    public void setPlatformName(String platformName) {
        this.platformName = platformName == null ? null : platformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_platform.platform_icon
     *
     * @return the value of pay_platform.platform_icon
     *
     * @mbggenerated
     */
    public String getPlatformIcon() {
        return platformIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_platform.platform_icon
     *
     * @param platformIcon the value for pay_platform.platform_icon
     *
     * @mbggenerated
     */
    public void setPlatformIcon(String platformIcon) {
        this.platformIcon = platformIcon == null ? null : platformIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_platform.status
     *
     * @return the value of pay_platform.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_platform.status
     *
     * @param status the value for pay_platform.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_platform.create_time
     *
     * @return the value of pay_platform.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_platform.create_time
     *
     * @param createTime the value for pay_platform.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_platform.update_time
     *
     * @return the value of pay_platform.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_platform.update_time
     *
     * @param updateTime the value for pay_platform.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}