package com.pet.lxw.pojo;

import java.util.Date;

public class ArticleSupport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_support.support_id
     *
     * @mbggenerated
     */
    private Integer supportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_support.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_support.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_support.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_support.support_id
     *
     * @return the value of article_support.support_id
     *
     * @mbggenerated
     */
    public Integer getSupportId() {
        return supportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_support.support_id
     *
     * @param supportId the value for article_support.support_id
     *
     * @mbggenerated
     */
    public void setSupportId(Integer supportId) {
        this.supportId = supportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_support.customer_id
     *
     * @return the value of article_support.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_support.customer_id
     *
     * @param customerId the value for article_support.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_support.create_time
     *
     * @return the value of article_support.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_support.create_time
     *
     * @param createTime the value for article_support.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_support.article_id
     *
     * @return the value of article_support.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_support.article_id
     *
     * @param articleId the value for article_support.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
}