package com.pet.lxw.pojo;

public class ArticleLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.al_id
     *
     * @mbggenerated
     */
    private Integer alId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.label_id
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.al_id
     *
     * @return the value of article_label.al_id
     *
     * @mbggenerated
     */
    public Integer getAlId() {
        return alId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.al_id
     *
     * @param alId the value for article_label.al_id
     *
     * @mbggenerated
     */
    public void setAlId(Integer alId) {
        this.alId = alId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.article_id
     *
     * @return the value of article_label.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.article_id
     *
     * @param articleId the value for article_label.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.label_id
     *
     * @return the value of article_label.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.label_id
     *
     * @param labelId the value for article_label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.status
     *
     * @return the value of article_label.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.status
     *
     * @param status the value for article_label.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}