package com.pet.lxw.pojo;

import java.util.Date;

public class ArticleCommentary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.commentary_id
     *
     * @mbggenerated
     */
    private Integer commentaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.commentary_content
     *
     * @mbggenerated
     */
    private String commentaryContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_commentary.father_id
     *
     * @mbggenerated
     */
    private Integer fatherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.commentary_id
     *
     * @return the value of article_commentary.commentary_id
     *
     * @mbggenerated
     */
    public Integer getCommentaryId() {
        return commentaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.commentary_id
     *
     * @param commentaryId the value for article_commentary.commentary_id
     *
     * @mbggenerated
     */
    public void setCommentaryId(Integer commentaryId) {
        this.commentaryId = commentaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.customer_id
     *
     * @return the value of article_commentary.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.customer_id
     *
     * @param customerId the value for article_commentary.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.user_id
     *
     * @return the value of article_commentary.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.user_id
     *
     * @param userId the value for article_commentary.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.article_id
     *
     * @return the value of article_commentary.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.article_id
     *
     * @param articleId the value for article_commentary.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.commentary_content
     *
     * @return the value of article_commentary.commentary_content
     *
     * @mbggenerated
     */
    public String getCommentaryContent() {
        return commentaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.commentary_content
     *
     * @param commentaryContent the value for article_commentary.commentary_content
     *
     * @mbggenerated
     */
    public void setCommentaryContent(String commentaryContent) {
        this.commentaryContent = commentaryContent == null ? null : commentaryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.create_time
     *
     * @return the value of article_commentary.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.create_time
     *
     * @param createTime the value for article_commentary.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.status
     *
     * @return the value of article_commentary.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.status
     *
     * @param status the value for article_commentary.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_commentary.father_id
     *
     * @return the value of article_commentary.father_id
     *
     * @mbggenerated
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_commentary.father_id
     *
     * @param fatherId the value for article_commentary.father_id
     *
     * @mbggenerated
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }
}