package com.pet.lxw.pojo;

/**
 *
 */
public class GoodsCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_collection.collection_id
     *
     * @mbggenerated
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_collection.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_collection.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_collection.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_collection.collection_id
     *
     * @return the value of goods_collection.collection_id
     *
     * @mbggenerated
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_collection.collection_id
     *
     * @param collectionId the value for goods_collection.collection_id
     *
     * @mbggenerated
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_collection.goods_id
     *
     * @return the value of goods_collection.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_collection.goods_id
     *
     * @param goodsId the value for goods_collection.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_collection.customer_id
     *
     * @return the value of goods_collection.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_collection.customer_id
     *
     * @param customerId the value for goods_collection.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_collection.status
     *
     * @return the value of goods_collection.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_collection.status
     *
     * @param status the value for goods_collection.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}