package com.pet.lxw.pojo;

import java.util.Date;

public class OrderGoodsEvaluation {

    private Integer evaluationId;
    private Integer ogId;
    private Integer customerId;
    private Integer goodsId;
    private String evaluationContent;
    private Date createTime;
    private Boolean status;
    private Integer fatherId;
    private Integer userId;
    private Boolean type;

    @Override
    public String toString() {
        return "OrderGoodsEvaluation{" +
                "evaluationId=" + evaluationId +
                ", ogId=" + ogId +
                ", customerId=" + customerId +
                ", goodsId=" + goodsId +
                ", evaluationContent='" + evaluationContent + '\'' +
                ", createTime=" + createTime +
                ", status=" + status +
                ", fatherId=" + fatherId +
                ", userId=" + userId +
                ", type=" + type +
                '}';
    }

    public Integer getEvaluationId() {
        return evaluationId;
    }

    public void setEvaluationId(Integer evaluationId) {
        this.evaluationId = evaluationId;
    }

    public Integer getOgId() {
        return ogId;
    }

    public void setOgId(Integer ogId) {
        this.ogId = ogId;
    }

    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Integer getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    public String getEvaluationContent() {
        return evaluationContent;
    }

    public void setEvaluationContent(String evaluationContent) {
        this.evaluationContent = evaluationContent == null ? null : evaluationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.create_time
     *
     * @return the value of order_goods_evaluation.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.create_time
     *
     * @param createTime the value for order_goods_evaluation.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.status
     *
     * @return the value of order_goods_evaluation.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.status
     *
     * @param status the value for order_goods_evaluation.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.father_id
     *
     * @return the value of order_goods_evaluation.father_id
     *
     * @mbggenerated
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.father_id
     *
     * @param fatherId the value for order_goods_evaluation.father_id
     *
     * @mbggenerated
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.user_id
     *
     * @return the value of order_goods_evaluation.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.user_id
     *
     * @param userId the value for order_goods_evaluation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.type
     *
     * @return the value of order_goods_evaluation.type
     *
     * @mbggenerated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.type
     *
     * @param type the value for order_goods_evaluation.type
     *
     * @mbggenerated
     */
    public void setType(Boolean type) {
        this.type = type;
    }
}