package com.pet.lxw.pojo;

import java.util.Date;

public class OrderGoodsEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.evaluation_id
     *
     * @mbggenerated
     */
    private Integer evaluationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.og_id
     *
     * @mbggenerated
     */
    private Integer ogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.evaluation_content
     *
     * @mbggenerated
     */
    private String evaluationContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.father_id
     *
     * @mbggenerated
     */
    private Integer fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_evaluation.type
     *
     * @mbggenerated
     */
    private Boolean type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.evaluation_id
     *
     * @return the value of order_goods_evaluation.evaluation_id
     *
     * @mbggenerated
     */
    public Integer getEvaluationId() {
        return evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.evaluation_id
     *
     * @param evaluationId the value for order_goods_evaluation.evaluation_id
     *
     * @mbggenerated
     */
    public void setEvaluationId(Integer evaluationId) {
        this.evaluationId = evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.og_id
     *
     * @return the value of order_goods_evaluation.og_id
     *
     * @mbggenerated
     */
    public Integer getOgId() {
        return ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.og_id
     *
     * @param ogId the value for order_goods_evaluation.og_id
     *
     * @mbggenerated
     */
    public void setOgId(Integer ogId) {
        this.ogId = ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.customer_id
     *
     * @return the value of order_goods_evaluation.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.customer_id
     *
     * @param customerId the value for order_goods_evaluation.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.goods_id
     *
     * @return the value of order_goods_evaluation.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.goods_id
     *
     * @param goodsId the value for order_goods_evaluation.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.evaluation_content
     *
     * @return the value of order_goods_evaluation.evaluation_content
     *
     * @mbggenerated
     */
    public String getEvaluationContent() {
        return evaluationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.evaluation_content
     *
     * @param evaluationContent the value for order_goods_evaluation.evaluation_content
     *
     * @mbggenerated
     */
    public void setEvaluationContent(String evaluationContent) {
        this.evaluationContent = evaluationContent == null ? null : evaluationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.create_time
     *
     * @return the value of order_goods_evaluation.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.create_time
     *
     * @param createTime the value for order_goods_evaluation.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.status
     *
     * @return the value of order_goods_evaluation.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.status
     *
     * @param status the value for order_goods_evaluation.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.father_id
     *
     * @return the value of order_goods_evaluation.father_id
     *
     * @mbggenerated
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.father_id
     *
     * @param fatherId the value for order_goods_evaluation.father_id
     *
     * @mbggenerated
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.user_id
     *
     * @return the value of order_goods_evaluation.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.user_id
     *
     * @param userId the value for order_goods_evaluation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_evaluation.type
     *
     * @return the value of order_goods_evaluation.type
     *
     * @mbggenerated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_evaluation.type
     *
     * @param type the value for order_goods_evaluation.type
     *
     * @mbggenerated
     */
    public void setType(Boolean type) {
        this.type = type;
    }
}