package com.pet.hpq.mapper;

import com.pet.hpq.dto.TOrderDto;
import com.pet.hpq.pojo.TOrder;
import com.pet.hpq.vo.OrderInfoVo;
import com.pet.yh.pojo.Customer;

import java.util.List;

public interface TOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int insert(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int insertSelective(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    TOrder selectByPrimaryKey(Integer orderId);

    List<TOrderDto> getOrdersByCustomId(OrderInfoVo orderInfoVo);

    int delivery(TOrder tOrder);

    int getOrderCount(int customerId);

    int getStatus(String orderNumber);

    int refuseOrder(TOrder tOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrder record);
}