package com.pet.hpq.pojo;

public class OrderGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.og_id
     *
     * @mbggenerated
     */
    private Integer ogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.total_price
     *
     * @mbggenerated
     */
    private Double totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.og_id
     *
     * @return the value of order_goods.og_id
     *
     * @mbggenerated
     */
    public Integer getOgId() {
        return ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.og_id
     *
     * @param ogId the value for order_goods.og_id
     *
     * @mbggenerated
     */
    public void setOgId(Integer ogId) {
        this.ogId = ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_id
     *
     * @return the value of order_goods.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_id
     *
     * @param orderId the value for order_goods.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_id
     *
     * @return the value of order_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_id
     *
     * @param goodsId the value for order_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.number
     *
     * @return the value of order_goods.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.number
     *
     * @param number the value for order_goods.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.price
     *
     * @return the value of order_goods.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.price
     *
     * @param price the value for order_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.total_price
     *
     * @return the value of order_goods.total_price
     *
     * @mbggenerated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.total_price
     *
     * @param totalPrice the value for order_goods.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
}