package com.pet.hpq.pojo;

import java.util.Date;

public class SalesReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.return_id
     *
     * @mbggenerated
     */
    private Integer returnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.og_id
     *
     * @mbggenerated
     */
    private Integer ogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.apply_desc
     *
     * @mbggenerated
     */
    private String applyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.refuse_desc
     *
     * @mbggenerated
     */
    private String refuseDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.return_id
     *
     * @return the value of sales_return.return_id
     *
     * @mbggenerated
     */
    public Integer getReturnId() {
        return returnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.return_id
     *
     * @param returnId the value for sales_return.return_id
     *
     * @mbggenerated
     */
    public void setReturnId(Integer returnId) {
        this.returnId = returnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.og_id
     *
     * @return the value of sales_return.og_id
     *
     * @mbggenerated
     */
    public Integer getOgId() {
        return ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.og_id
     *
     * @param ogId the value for sales_return.og_id
     *
     * @mbggenerated
     */
    public void setOgId(Integer ogId) {
        this.ogId = ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.customer_id
     *
     * @return the value of sales_return.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.customer_id
     *
     * @param customerId the value for sales_return.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.status
     *
     * @return the value of sales_return.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.status
     *
     * @param status the value for sales_return.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.create_time
     *
     * @return the value of sales_return.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.create_time
     *
     * @param createTime the value for sales_return.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.update_time
     *
     * @return the value of sales_return.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.update_time
     *
     * @param updateTime the value for sales_return.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.apply_desc
     *
     * @return the value of sales_return.apply_desc
     *
     * @mbggenerated
     */
    public String getApplyDesc() {
        return applyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.apply_desc
     *
     * @param applyDesc the value for sales_return.apply_desc
     *
     * @mbggenerated
     */
    public void setApplyDesc(String applyDesc) {
        this.applyDesc = applyDesc == null ? null : applyDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.user_id
     *
     * @return the value of sales_return.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.user_id
     *
     * @param userId the value for sales_return.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.refuse_desc
     *
     * @return the value of sales_return.refuse_desc
     *
     * @mbggenerated
     */
    public String getRefuseDesc() {
        return refuseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.refuse_desc
     *
     * @param refuseDesc the value for sales_return.refuse_desc
     *
     * @mbggenerated
     */
    public void setRefuseDesc(String refuseDesc) {
        this.refuseDesc = refuseDesc == null ? null : refuseDesc.trim();
    }
}