package com.pet.lxw.mapper;


import com.pet.lxw.pojo.ArticleCommentary;

public interface ArticleCommentaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_commentary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_commentary
     *
     * @mbggenerated
     */
    int insert(ArticleCommentary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_commentary
     *
     * @mbggenerated
     */
    int insertSelective(ArticleCommentary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_commentary
     *
     * @mbggenerated
     */
    ArticleCommentary selectByPrimaryKey(Integer commentaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_commentary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleCommentary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_commentary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleCommentary record);
}