package com.pet.lxw.mapper;

import com.qf.pojo.ArticleLabel;
import com.qf.pojo.ArticleLabelExample;
import java.util.List;

public interface ArticleLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer alId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    int insert(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    int insertSelective(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    List<ArticleLabel> selectByExample(ArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    ArticleLabel selectByPrimaryKey(Integer alId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleLabel record);
}