package com.pet.lxw.mapper;


import com.pet.lxw.pojo.GoodsCollection;

public interface GoodsCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_collection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_collection
     *
     * @mbggenerated
     */
    int insert(GoodsCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_collection
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_collection
     *
     * @mbggenerated
     */
    GoodsCollection selectByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_collection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCollection record);
}