package com.pet.lxw.mapper;

import com.pet.lxw.pojo.OrderGoodsEvaluation;

public interface OrderGoodsEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_evaluation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_evaluation
     *
     * @mbggenerated
     */
    int insert(OrderGoodsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_evaluation
     *
     * @mbggenerated
     */
    int insertSelective(OrderGoodsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_evaluation
     *
     * @mbggenerated
     */
    OrderGoodsEvaluation selectByPrimaryKey(Integer evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderGoodsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderGoodsEvaluation record);
}