package com.pet.lxw.mapper;

import com.pet.lxw.pojo.ShippingAddress;

import java.util.List;

public interface ShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_address
     *
     * @mbggenerated
     */
    int delAddress(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_address
     *
     * @mbggenerated
     */
    int addAddress(ShippingAddress shippingAddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_address
     *
     * @mbggenerated
     */
    int insertSelective(ShippingAddress record);




    List<ShippingAddress> selectFromAddress(int customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_address
     *
     * @mbggenerated
     */
    int updateAddress(ShippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShippingAddress record);
}