package com.pet.yxy.pojo;

import java.util.Date;

public class CustomerMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.message_id
     *
     * @mbggenerated
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.message_type
     *
     * @mbggenerated
     */
    private Byte messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.is_readed
     *
     * @mbggenerated
     */
    private Boolean isReaded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_message.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.message_id
     *
     * @return the value of customer_message.message_id
     *
     * @mbggenerated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.message_id
     *
     * @param messageId the value for customer_message.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.customer_id
     *
     * @return the value of customer_message.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.customer_id
     *
     * @param customerId the value for customer_message.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.message_type
     *
     * @return the value of customer_message.message_type
     *
     * @mbggenerated
     */
    public Byte getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.message_type
     *
     * @param messageType the value for customer_message.message_type
     *
     * @mbggenerated
     */
    public void setMessageType(Byte messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.content
     *
     * @return the value of customer_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.content
     *
     * @param content the value for customer_message.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.status
     *
     * @return the value of customer_message.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.status
     *
     * @param status the value for customer_message.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.is_readed
     *
     * @return the value of customer_message.is_readed
     *
     * @mbggenerated
     */
    public Boolean getIsReaded() {
        return isReaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.is_readed
     *
     * @param isReaded the value for customer_message.is_readed
     *
     * @mbggenerated
     */
    public void setIsReaded(Boolean isReaded) {
        this.isReaded = isReaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_message.create_time
     *
     * @return the value of customer_message.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_message.create_time
     *
     * @param createTime the value for customer_message.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}